on:
    push:
        branches:
            - main
name: Deploy website
jobs:
    web-deploy:
        name: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Get Latest code
              uses: actions/checkout@v3
            - name: Build Project
              run: |
                  npm install
                  npm run build
            - name: Sync Files
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: 185.181.165.6
                  username: zats
                  password: Pa3wtj1X
                  server-dir: www/razdev.online/gh-actions/
                  exclude: |
                      **/app/**
                      **.gitignore**
                      **gulpfile.js**
                      **package.json**
                      **package-lock.json**
                      **/node_modules/**
                      **/.git/**
